on: issue_comment

jobs:
  pr_commented:
    # This job only runs for pull request comments
    name: PR comment

    permissions:
      contents: read
      id-token: write
      pull-requests: write

    runs-on: ubuntu-latest
    if: ${{ github.event.issue.pull_request && github.event.comment.body == 'create_package' && github.event.issue.state == 'open' }}
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9.x'
          architecture: 'x64'
      - uses: actions/checkout@v3
        with:
          ref: refs/pull/${{github.event.issue.number}}/merge
          fetch-depth: 0
      - name: Import Secrets
        uses: hashicorp/vault-action@v2.4.2
        with:
          url: https://hashicorp-vault.production.sneaksanddata.com/
          role: github
          method: jwt
          secrets: |
            /secret/data/common/package-publishing/aws-ca/production/artifact-user access_key ;
            /secret/data/common/package-publishing/aws-ca/production/artifact-user access_key_id ;
      - name: Setup AWS CA
        uses: SneaksAndData/github-actions/setup_aws_ca@v0.1.9
        with:
          aws_access_key: ${{ env.ACCESS_KEY }}
          aws_access_key_id: ${{ env.ACCESS_KEY_ID }}
          mode: publish
          aws_ca_domain: esd-code-artifact-production
          aws_ca_domain_owner: 497010676583
          aws_ca_repository: esd-artifacts
        id: setup_aws_ca
      - name: Install Poetry and dependencies
        uses: SneaksAndData/github-actions/install_poetry@v0.1.9
        with:
          pypi_repo_url: ${{ steps.setup_aws_ca.outputs.url }}
          pypi_token_username: ${{ steps.setup_aws_ca.outputs.user }}
          pypi_token: ${{ steps.setup_aws_ca.outputs.token }}
          install_extras: all
      - name: Create package
        uses: SneaksAndData/github-actions/create_package@v0.1.9
        with:
          repo_url: ${{ steps.setup_aws_ca.outputs.url }}
          repo_token_username: ${{ steps.setup_aws_ca.outputs.user }}
          repo_token: ${{ steps.setup_aws_ca.outputs.token }}
          package_name: anti_clustering
