name: Release a new version

on: workflow_dispatch

jobs:
  create_release:
    name: Create release
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: SneaksAndData/github-actions/semver_release@v0.1.9
        with:
          major_v: 0
          minor_v: 4
